# ============================================================
# Bilibili
# Quantumult X Rewrite
# ============================================================


# ------------------------------------------------------------
# Homepage Feed
# ------------------------------------------------------------

# 首页：
# - 广告
# - 直播
# - 图文 / 专栏
# - < 15 分钟视频
# - 关键词 / 人物 / UP 主过滤
^https:\/\/app\.bilibili\.com\/x\/v2\/feed\/index url script-response-body https://raw.githubusercontent.com/alyxchm1/qx-public/main/scripts/bilibili/bilibili-feed-filter.js


# ------------------------------------------------------------
# Search
# ------------------------------------------------------------

# 搜索广场 / 搜索推荐：完全清空
^https:\/\/app\.bilibili\.com\/x\/v2\/search\/square url reject-200


# ------------------------------------------------------------
# Live
# ------------------------------------------------------------

# 直播 Feed
^https:\/\/api\.live\.bilibili\.com\/xlive\/app-interface\/v2\/index\/feed url script-response-body https://raw.githubusercontent.com/alyxchm1/qx-public/main/scripts/bilibili/bilibili-live-filter.js













# ------------以下是其他作者的更新----------------

# ------------------------------------------------------------
# Popular - Protobuf
# ------------------------------------------------------------

# 热门页：
# - 热搜
# - 广告推荐卡
# - UP 主关注推荐卡
^https:\/\/(grpc\.biliapi\.net|app\.bilibili\.com)\/bilibili\.app\.show\.v1\.Popular\/Index$ url script-response-body https://raw.githubusercontent.com/kokoryh/Script/master/js/bilibili.protobuf.js


# ------------------------------------------------------------
# View - Protobuf
# ------------------------------------------------------------

# 播放页：
# - 标题前标签
# - 充电按钮
# - 活动标签
^https:\/\/(grpc\.biliapi\.net|app\.bilibili\.com)\/bilibili\.app\.(view|viewunite)\.v1\.View\/(View|ViewProgress)$ url script-response-body https://raw.githubusercontent.com/kokoryh/Script/master/js/bilibili.protobuf.js


# ------------------------------------------------------------
# MITM
# ------------------------------------------------------------

hostname = app.bilibili.com, api.live.bilibili.com, grpc.biliapi.net