# 首页推荐流
^https:\/\/app\.bilibili\.com\/x\/v2\/feed\/index url script-response-body https://raw.githubusercontent.com/alyxchm1/qx-public/main/scripts/bilibili/bilibili-feed-filter.js

# 直播 Feed
^https:\/\/api\.live\.bilibili\.com\/xlive\/app-interface\/v2\/index\/feed url script-response-body https://raw.githubusercontent.com/alyxchm1/qx-public/main/scripts/bilibili/bilibili-live-filter.js

# 热搜：完全拒绝
^https:\/\/app\.bilibili\.com\/x\/v2\/search\/square url reject

hostname = app.bilibili.com, api.live.bilibili.com